services:
  aiogram:
    build: .
    container_name: bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    networks:
      - 2eden_network
    volumes:
      - ./source:/home

networks:
  2eden_network: